version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: expense-tracker-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: expense
      POSTGRES_PASSWORD: expense123
      POSTGRES_DB: expense_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: